theme: minima
title: Fourty-Two
author: Yash Suryawanshi
email: curiyash19@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I plan to write about science, technology and grand scheme of things. Wherever, Whenever?, However you are, "Don't panic!", as Douglas Adams once wrote.
 Your towel is right beside you!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  curiyash # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
